// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxc8-Ci-1OV2PRAVbTcBSNhjwym_PfffE',
    appId: '1:831073843954:web:a0fad14a13ca96eb902e6b',
    messagingSenderId: '831073843954',
    projectId: 'hash-e-commerce',
    authDomain: 'hash-e-commerce.firebaseapp.com',
    storageBucket: 'hash-e-commerce.appspot.com',
    measurementId: 'G-62W5GDBZKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBui5UdBQGjvphw7-xeBs8JXKql86W5w7Y',
    appId: '1:831073843954:android:084c397fc9cb1b71902e6b',
    messagingSenderId: '831073843954',
    projectId: 'hash-e-commerce',
    storageBucket: 'hash-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrKJhNDi8tQimepbKpNGBov9fMTz6NYmM',
    appId: '1:831073843954:ios:236a4304595fff02902e6b',
    messagingSenderId: '831073843954',
    projectId: 'hash-e-commerce',
    storageBucket: 'hash-e-commerce.appspot.com',
    iosClientId: '831073843954-f52pnq6ftvg97i4k9amh4h1sdk9p0qfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hashEcommerceUserSideapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrKJhNDi8tQimepbKpNGBov9fMTz6NYmM',
    appId: '1:831073843954:ios:8b54917f5d6f1a7c902e6b',
    messagingSenderId: '831073843954',
    projectId: 'hash-e-commerce',
    storageBucket: 'hash-e-commerce.appspot.com',
    iosClientId: '831073843954-3guci7dicrg33sg2i2mrvhp2ghi9t7ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.hashEcommerceUserSideapp.RunnerTests',
  );
}
